services:
  - type: web
    name: risol-mayo-app
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        value: https://ylekchhoxdjqliajksnb.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsZWtjaGhveGRqcWxpYWprc25iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NDM5NTIsImV4cCI6MjA4NjExOTk1Mn0.8_4A8rqhBknXotZIhKL_W83fPzbrF7vXjvc-lu9EFbI
